added webpack
cenetp/roomconf-editor pull request #1
Opened 2020-07-31 11:55 UTC by karimould

2020-08-01 18:51 UTC, cenetp requested changes

2020-08-01 18:51 UTC, cenetp commented on package.json
> +  "license": "ISC",
Die richtige Lizenz ist MIT :)

2020-08-01 18:51 UTC, cenetp commented on js/app.js
> +    size: 3,
Das muss zurück auf 30, sonst ist die initiale Größe der Bubble zu klein

2020-08-01 18:51 UTC, cenetp commented on js/app.js
> +      size: 3,
Das muss zurück auf 18

2020-08-01 18:51 UTC, cenetp commented on js/app.js
> +    width: 1,
Das muss zurück auf 3

2020-08-01 18:51 UTC, cenetp commented on js/app.js
> +      size: 3,
Das muss zurück auf 18

2020-08-01 18:51 UTC, cenetp commented on js/app.js
> +      size: isNaN(parseInt(a)) ? 3 : parseInt(a) * 3 >= 81 ? 81 : parseInt(a) * 3 < 21 ? 21 : parseInt(a) * 3,
Das muss zurück auf 30

2020-08-01 18:51 UTC, cenetp commented on js/app.js
> +    console.log("DRIN", node);
Löschen :)

2020-08-02 16:29 UTC, cenetp requested changes
Aktualisiertes Review.

2020-08-02 16:37 UTC, cenetp requested changes
Values für `del` und `back`

2020-08-02 16:37 UTC, cenetp commented on js/app.js
> +    edgeDescription: "Click on a room and drag the edge to another room to connect them.",
Hier noch folgende Properties hinzufügen (die sind jetzt `undefined` geworden):

```
del: 'Delete selected',
back: 'Back',
```

2020-08-04 17:37 UTC, closed without merging

2020-08-04 17:38 UTC, karimould commented
will be merged in seperate dev branch